#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const args = parseArgs(process.argv.slice(2));

if (args.help || args.h) {
	usage();
	process.exit(0);
}

const projectRoot = path.resolve(__dirname, "../..");
const outputArg = args.output || path.join(projectRoot, "export_presets.cfg");
const output = outputArg === "-" ? "-" : path.resolve(outputArg);
const packageId = String(args.package || process.env.PACKAGE || "org.godotengine.godotxrfoundation");
const bundleId = String(args.bundle || process.env.BUNDLE_ID || packageId);
const teamId = String(args["team-id"] || process.env.TEAM_ID || "");
const force = Boolean(args.force);
const dryRun = Boolean(args["dry-run"]);

if (fs.existsSync(output) && !force && !dryRun) {
	console.error(`Refusing to overwrite existing file: ${output}`);
	console.error("Pass --force to replace it, or --output <file> to write a separate starter file.");
	process.exit(1);
}

const content = renderTemplate({ packageId, bundleId, teamId });

if (dryRun || output === "-") {
	process.stdout.write(content);
} else {
	fs.mkdirSync(path.dirname(output), { recursive: true });
	fs.writeFileSync(output, content, "utf8");
	console.log(`Wrote ${output}`);
	console.log("Next:");
	console.log(`  node tools/c00/check_export_presets.js --gate all --file ${relativeToProject(output)}`);
	console.log("  Open the project in Godot, review platform-specific export options, then re-save the presets.");
}


function parseArgs(argv) {
	const parsed = {};
	for (let index = 0; index < argv.length; index += 1) {
		const item = argv[index];
		if (!item.startsWith("--")) {
			continue;
		}
		const key = item.slice(2);
		const next = argv[index + 1];
		if (!next || next.startsWith("--")) {
			parsed[key] = true;
		} else {
			parsed[key] = next;
			index += 1;
		}
	}
	return parsed;
}


function usage() {
	console.error([
		"Usage:",
		"  node tools/c00/write_export_presets_template.js [--output export_presets.cfg] [--force]",
		"",
		"Options:",
		"  --package <id>    Android package id. Default: org.godotengine.godotxrfoundation",
		"  --bundle <id>     iOS bundle id. Default: same as package id",
		"  --team-id <id>    Optional Apple team id placeholder.",
		"  --dry-run         Print the template without writing.",
	].join("\n"));
}


function relativeToProject(filePath) {
	const relative = path.relative(projectRoot, filePath);
	if (!relative.startsWith("..")) {
		return relative || ".";
	}
	return filePath;
}


function quoted(value) {
	return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}


function renderTemplate(values) {
	const packageId = quoted(values.packageId);
	const bundleId = quoted(values.bundleId);
	const teamId = quoted(values.teamId);

	return `# C00 starter export presets.
# Generated by tools/c00/write_export_presets_template.js.
# Review these presets in the Godot editor before shipping. Signing secrets belong in .godot/export_credentials.cfg.

[preset.0]

name="C00 Rokid OpenXR"
platform="Android"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="builds/rokid/c00.apk"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

custom_template/debug=""
custom_template/release=""
gradle_build/use_gradle_build=true
architectures/armeabi-v7a=false
architectures/arm64-v8a=true
package/unique_name=${packageId}
package/name="GodotXRFoundation"
version/code=1
version/name="0.0.1-c00"
xr_features/xr_mode=1
screen/immersive_mode=true
command_line/extra_args="--xr-platform=rokid"
permissions/camera=true

[preset.1]

name="C00 Android ARCore"
platform="Android"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="builds/android_arcore/c00.apk"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.1.options]

custom_template/debug=""
custom_template/release=""
gradle_build/use_gradle_build=true
architectures/armeabi-v7a=false
architectures/arm64-v8a=true
package/unique_name=${packageId}
package/name="GodotXRFoundation"
version/code=1
version/name="0.0.1-c00"
xr_features/xr_mode=0
screen/immersive_mode=true
command_line/extra_args="--xr-platform=arcore"
permissions/camera=true
plugins/GodotARCore=true

[preset.2]

name="C00 iPad ARKit"
platform="iOS"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="builds/ipad/c00.zip"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.2.options]

custom_template/debug=""
custom_template/release=""
architectures/arm64=true
application/bundle_identifier=${bundleId}
application/short_version="0.0.1"
application/version="1"
application/signature/team_id=${teamId}
privacy/camera_usage_description="C00 uses the camera for ARKit tracking."
capabilities/arkit=true
plugins/GodotARKit=true
command_line/extra_args="--xr-platform=ipad"
`;
}
