#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "../..");
const presetsFile = path.join(root, "export_presets.cfg");
const credentialsFile = path.join(root, ".godot", "export_credentials.cfg");

const debugKeystore = requiredEnv("GODOT_ANDROID_KEYSTORE_DEBUG_PATH");
const debugUser = requiredEnv("GODOT_ANDROID_KEYSTORE_DEBUG_USER");
const debugPassword = requiredEnv("GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD");

if (!fs.existsSync(presetsFile)) {
	console.error(`Missing export presets: ${presetsFile}`);
	process.exit(2);
}

const presets = parseAndroidPresetSections(fs.readFileSync(presetsFile, "utf8"));
if (presets.length === 0) {
	console.error("No Android export presets found; nothing to write.");
	process.exit(2);
}

const lines = [
	"; Generated by tools/c00/write_godot_export_credentials.js.",
	"; Local Android debug signing credentials for C00 device exports.",
	"; This file lives under .godot/ and must not be committed.",
	"",
];

for (const section of presets) {
	lines.push(`[${section}.options]`);
	lines.push(`keystore/debug=${quoteGodotString(debugKeystore)}`);
	lines.push(`keystore/debug_user=${quoteGodotString(debugUser)}`);
	lines.push(`keystore/debug_password=${quoteGodotString(debugPassword)}`);
	lines.push("");
}

fs.mkdirSync(path.dirname(credentialsFile), { recursive: true });
fs.writeFileSync(credentialsFile, `${lines.join("\n").replace(/\s+$/, "")}\n`, "utf8");

console.log(`configured Godot export credentials: ${credentialsFile}`);
for (const section of presets) {
	console.log(`configured ${section}.options keystore/debug=${debugKeystore}`);
	console.log(`configured ${section}.options keystore/debug_user=${debugUser}`);
	console.log(`configured ${section}.options keystore/debug_password=<hidden>`);
}

function parseAndroidPresetSections(text) {
	const sections = [];
	let currentSection = "";
	let currentPlatform = "";
	for (const line of text.split(/\r?\n/)) {
		const sectionMatch = /^\[(preset\.\d+)\]$/.exec(line.trim());
		if (sectionMatch) {
			if (currentSection && currentPlatform === "Android") {
				sections.push(currentSection);
			}
			currentSection = sectionMatch[1];
			currentPlatform = "";
			continue;
		}
		if (/^\[preset\.\d+\.options\]$/.test(line.trim())) {
			if (currentSection && currentPlatform === "Android") {
				sections.push(currentSection);
			}
			currentSection = "";
			currentPlatform = "";
			continue;
		}
		if (currentSection) {
			const platformMatch = /^platform\s*=\s*"([^"]+)"\s*$/.exec(line.trim());
			if (platformMatch) {
				currentPlatform = platformMatch[1];
			}
		}
	}
	if (currentSection && currentPlatform === "Android") {
		sections.push(currentSection);
	}
	return Array.from(new Set(sections));
}

function requiredEnv(name) {
	const value = process.env[name];
	if (!value) {
		console.error(`Missing environment value: ${name}`);
		process.exit(2);
	}
	return value;
}

function quoteGodotString(value) {
	return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
