#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat <<EOF
GodotARKit.xcframework is not generated by this repository yet.

This skeleton defines the singleton API and ARKit session logic used by NativeXRProvider.
To produce the binary:

1. Create an Objective-C++ static library target in Xcode named GodotARKit.
2. Add src/GodotARKitPlugin.mm and src/GodotARKitSession.mm.
3. Add Godot iOS export template headers to HEADER_SEARCH_PATHS.
4. Link Foundation, UIKit, ARKit, CoreMotion, and Metal.
5. Build device and simulator static libraries.
6. Run:

   xcodebuild -create-xcframework \\
     -library <device>/libGodotARKit.a \\
     -library <simulator>/libGodotARKit.a \\
     -output "$ROOT/GodotARKit.xcframework"

Then copy:

   cp "$ROOT/GodotARKit.gdip.template" "$ROOT/GodotARKit.gdip"

EOF
